name: Emacs Test Box 

on:
  push:
    branches: 
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 24.1
          - 24.2
          - 24.3
          - 24.4
          - 24.5
          - 25.1        
          - 25.2
          - 25.3
          - 26.1
          - 26.2
          - 26.3
          - 27.1
          - 27.2
          - 28.1
          - snapshot
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Emacs
      uses: purcell/setup-emacs@v3.0
      with:
        version: ${{ matrix.emacs_version }}
        
    - uses: actions/cache@v2
        id: cache-cask-packages
        with:
          path: .cask
          key: cache-cask-packages-000
    - uses: actions/cache@v2
        id: cache-cask-executable
        with:
          path: ~/.cask
          key: cache-cask-executable-000
    - uses: cask/setup-cask@master
        if: steps.cache-cask-executable.outputs.cache-hit != 'true'
        with:
          version: snapshot
    - run: echo "$HOME/.cask/bin" >> $GITHUB_PATH        

    - name: Test
      run: |
        emacs --batch \
        -eval "(setq load-prefer-newer t)" \
        -eval "(add-to-list 'load-path \".\")" \
        -eval "()" \
        -l ert \
        -l scratch.el \
        -f ert-run-tests-batch-and-exit
